name: environment variables scope

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SUPER_SECRET: ${{ secrets.SUPER_SECRET }}

    steps:
      - name: Run1
        run: echo $SUPER_SECRET

      - name: Run2
        run: echo $SUPER_SECRET

      - name: Run2
        run: echo $HYPER_SECRET
        env:
          HYPER_SECRET: ${{ secrets.HYPER_SECRET }}

      - name: Run3
        run: echo $HYPER_SECRET
