name: Slash command debug

on:
  issue_comment:
    types: [created, edited]

jobs:
  rerun:
    runs-on: ubuntu-latest
    name: Re-run PR check workflow
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/rerun')

    steps:
      - name: Print PR Number
        run: |
          echo "${PR_NUMBER}"
        env:
          PR_NUMBER: ${{ github.event.number }}
