name: SSH Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
