name: test job

on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Check branch update
        run: ./script/check_branch.sh
        env:
          FEATURE_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
