name: test job

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check branch update
        run: ./script/check_branch.sh
        env:
          COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
